---
output:
  pdf_document: default
  html_document: default
---

# Concluding Remarks {-#conclusion}

---

The earliest image of the Chinese dragon is the Jade *Pig-Dragon* ring found in a ritualistic burial by the Hongshan culture. This piece gives the viewer a clue to the primitive idea of what was a dragon and the meaning the early Chinese cultures gave it. In later years the ritualistic context of the dragon continued through the Shang Dynasty, as a prominent symbol in the heavily decorated bronze ritualistic vessels. Yet its representation was overshadowed by the taotie, a monster figure that was highly feared and used during the Shang Dynasty. Soon later, in the Zhou Dynasty, the idea of fearing nature began to decline as dragon form decorations found on bronzes and precious jades became a symbol of wealth and luxury.

The dragon’s auspicious symbolism began to develop in the Qin Dynasty, which then became formalized in the cosmology of the Han prince Liu An who defined two of the five guardian beasts (Yellow Dragon, Azure Dragon, White Tiger, Vermillion Bird and Dark Warrior [Black Tortoise]) as dragons. Thus, the Han people saw the dragon as a protective symbol and guardian with great powers including immortality. Dragons maintained their auspicious status in the Tang Dynasty, but their appearance began to change drastically with the influx of foreign artistic concepts brought in by the Silk Road. The physical form of the dragon starts to become more serpentine, less animalistic, with longer tails and curling, “flying” forms. The Tang is also known for the importation of foreign religions like Buddhism from this period on, dragons will be supplanted into religious imagery, giving these religions their “Chinese” twist. 

Following these Tang developments, the unique form of the Chinese dragon was more concretely illustrated on dragon paintings of the Song and Yuan dynasty. This period saw a rise in new compositions and forms of not only the dragon, but also the envirnoment that the dragon was situated in. In the late imperial period of the Ming and the Qing, dragons maintained symbolic usage in religious art, but were more prominently used for political symbolism. This was a continuation of the Yuan dynasty’s use of five-clawed dragons as an imperial symbol, which both the Ming and Qing formalized to be exclusively used by members of the imperial family or court. From its appearance as the cryptic *Pig-Dragon* in Neolithic times to its imperial associations in the Ming and Qing dynasties, the enduring symbol of the Chinese dragon is firmly tied to Chinese art, and even to Chinese identity, as a whole.
