---
output:
  pdf_document: default
  html_document: default
---

# References {-}

---


1. (c. 3500 BC., Hongshan Culture, Neolithic period). Pig-Dragon Ring [Jade]. The National Museum of China, Beijing, China. 

2. (13th–11th century B.C., Shang Dynasty). Appliqué in the Form of a Dragon  [Bronze]. The Metropolitan Museum of Art, New York, United States.https://www.metmuseum.org/art/collection/search/49505 

3. (3rd century BC, Eastern Zhou Dynasty, Warring States period). Knotted Dragon Pendant [Jade (nephrite)]. The Metropolitan Museum, New York. https://www.metmuseum.org/art/collection/search/39637.

4. (206 BC – AD 9, Western Han Dynasty). Mirror
with Nipple and Dragon Design [Bronze]. The Metropolitan Museum, New York. https://www.metmuseum.org/art/collection/search/74429.

5. (Tang Dynasty). Mirror with Dragon [Bronze with Iron Core]. Shaanxi History Museum, Xi’an.

6. (c. 7th century AD)., Tang Dynasty). Jar with Dragon-Headed Handles [Stoneware]. The Metropolitan Museum, New York. https://www.metmuseum.org/art/collection/search/45862.

7. Chen R., (First Half of the 13th Century). Nine Dragons; Handscroll, ink on paper. Museum of Fine Arts Boston, Massachusetts, United States.

8. Zhang, Y. (C. Early 14th century) Beneficent Rain; Handscroll, ink on silk. The Metropolitan Museum of Art, New York, United States.

9. Purtle, J. (2016). The Pictorial Form of a Zoomorphic Ecology: Dragons and Their Painters in Song and Southern Song China. In Silbergeld J. & Wang E. (Eds.), The Zoomorphic Imagination in Chinese Art and Culture (pp. 253-288). Honolulu: University of Hawai'i Press. Retrieved December 7, 2020, from http://www.jstor.org/stable/j.ctvvn60j.13

10. Zhang Zhao et al., Shiqu baoji 32:82a; translation adapted from Hsien-chi Tseng, “A Study of the Nine Dragons Scroll,” Archives of the Chinese Art Society of America 11 (1957): 17–39, 19.

11. Tseng, H. (n.d.). A study of the Nine Dragons scroll.

12. Wenyuange siku quanshu neilian wangban 文淵閣四庫全書內聯網版 (Wenyuange siku quanshu [Complete library of four treasuries], electronic version). Hong Kong: Dizhi Digital Heritage Publishing, 2002.

13. Wilson, J. (1990). Powerful Form and Potent Symbol: The Dragon in Asia. The Bulletin of the Cleveland Museum of Art, 77(8), 286-323. Retrieved December 8, 2020, from http://www.jstor.org/stable/25161297

14. (c. 1522-1566, Ming Dynasty Jiajing period). Dish with character for longevity (shou). The Metropolitan Museum, New York. https://www.metmuseum.org/art/collection/search/40226.

15. (1403-1424, Ming Dynasty Yongle Period). Sutra box with dragons amid clouds. The Metropolitan Museum, New York.
https://www.metmuseum.org/art/collection/search/60870.

16. Nickel, H. (1991). The Dragon and the Peral. The Metropolitan Museum of Art. http://resources.metmuseum.org/resources/metpublications/pdf/The_Dragon_and_the_Pearl_The_Metropolitan_Museum_Journal_v_26_1991.pdf

17. U. (n.d.). View Scroll: East Asian Scroll Paintings. Retrieved December 2, 2020, from https://scrolls.uchicago.edu/view-scroll/49

